version: '3'
services:
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - 3000:3000
    stdin_open: true
    command: npx serve build